/* Traductions locales : aucun service de traduction externe. */
globalThis.BIRTHDAY_I18N = {
 fr: {
  title:'Juste pour toi, ma Tütüş',description:'Une lettre sous les étoiles, juste pour toi.',
  welcomeEyebrow:'JUSTE POUR TOI',welcomeTitle:'Avant de commencer…',welcomeNote:'Installe-toi confortablement. Cette lettre est pour toi.',languageQuestion:'Dans quelle langue veux-tu lire ta lettre ?',musicQuestion:'Veux-tu écouter la musique ?',musicYes:'Avec musique',musicNo:'Sans musique',start:'Entrer dans ma surprise ♡',loading:'La lettre arrive…',
  skip:'Aller au message',gateEyebrow:'UNE SURPRISE SOUS LES ÉTOILES',gateTitle:'Quelque chose de spécial|t’attend…',gateText:'Il y a quelque chose que je voulais te dire…|Mais pas tout de suite. ♡',countdownLabel:'Temps restant avant la surprise',opening:'Ouverture à 23:59, heure de Bulgarie',days:'jours',hours:'heures',minutes:'minutes',seconds:'secondes',
  brand:'pour toi,|Tütüş',masthead:'UNE LETTRE SOUS LES ÉTOILES',introEyebrow:'JUSTE POUR TOI, MA TÜTÜŞ',introTitle:'Il y a des mots|qui attendent|leur moment.',begin:'Découvrir ce que j’ai gardé pour toi ♡',scroll:'Fais défiler doucement',mysteryLabel:'Le mystère et la réponse',chapterOne:'LE MOMENT QUE J’ATTENDAIS',portraitChapter:'02 / ELLE',portraitTitle:'À travers|mes yeux.',togetherChapter:'03 / NOUS',togetherTitle:'Deux cœurs.|Une histoire.',letterChapter:'04 / TOUS MES MOTS, POUR TOI',letterTitle:'Ce que je veux|vraiment te dire.',readingOn:'Lire tout le message sans animations',readingOff:'Revenir à la lecture animée',letterLabel:'Mon message intégral',finalChapter:'05 / ET TOUTES LES ÉTOILES AVEC NOUS',finalTitle:'Joyeux anniversaire,|mon amour.',birthday:'Joyeux anniversaire, ma Tütüş',last:'Une dernière chose…',replay:'Revoir notre histoire ♡',footer:'Juste pour toi. Toujours avec amour.',
  musicPlay:'Activer la musique',musicPause:'Couper la musique',musicPlaying:'Musique : activée',musicPaused:'Musique : coupée',photoDialog:'Photo agrandie',closePhoto:'Fermer la photo',photoHint:'Échap ou toucher le fond pour fermer',photoHers:'Portrait de Tütüş',photoTogether:'Photo de nous deux',enlarge:'Agrandir',photoError:'Cette photo n’a pas pu se charger.',emptyPhotos:'Les photos prendront bientôt leur place ici.',emptyLetter:'La lettre sera bientôt ici.',lastFallback:'Je t’aime. Aujourd’hui, demain, et tous les jours.',loadError:'La lettre arrive… Vérifie ta connexion, puis réessaie.',retry:'Réessayer',noMusic:'La lettre se découvre aussi en silence.',
  excerptIntro:'Tu te demande',excerptStory:['Peut être il a oublié','Mais attends','je suis ton homme','ton Syrien n’avait rien oublié'],excerptPortrait:'J’aime ton sourire',excerptTogether:'On est deux personnes'
 },
 tr: {
  title:'Sadece senin için, Tütüşüm',description:'Yıldızların altında bir mektup, sadece senin için.',
  welcomeEyebrow:'SADECE SENİN İÇİN',welcomeTitle:'Başlamadan önce…',welcomeNote:'Rahatına bak. Bu mektup senin için.',languageQuestion:'Mektubunu hangi dilde okumak istersin?',musicQuestion:'Müzik dinlemek ister misin?',musicYes:'Müzikle',musicNo:'Müziksiz',start:'Sürprizimi keşfet ♡',loading:'Mektubun geliyor…',
  skip:'Mektuba geç',gateEyebrow:'YILDIZLARIN ALTINDA BİR SÜRPRİZ',gateTitle:'Seni çok özel|bir şey bekliyor…',gateText:'Sana söylemek istediğim bir şey var…|Ama henüz değil. ♡',countdownLabel:'Sürprize kalan süre',opening:'Bulgaristan saatiyle 23:59’da açılacak',days:'gün',hours:'saat',minutes:'dakika',seconds:'saniye',
  brand:'senin için,|Tütüş',masthead:'YILDIZLARIN ALTINDA BİR MEKTUP',introEyebrow:'SADECE SENİN İÇİN, TÜTÜŞÜM',introTitle:'Bazı sözler|kendi anını|bekler.',begin:'Senin için sakladığım şeyi keşfet ♡',scroll:'Yavaşça aşağı kaydır',mysteryLabel:'Gizem ve cevabı',chapterOne:'BEKLEDİĞİM AN',portraitChapter:'02 / SEN',portraitTitle:'Benim|gözlerimden.',togetherChapter:'03 / BİZ',togetherTitle:'İki kalp.|Bir hikâye.',letterChapter:'04 / BÜTÜN SÖZLERİM SENİN İÇİN',letterTitle:'Sana gerçekten|söylemek istediğim.',readingOn:'Mektubun tamamını animasyonsuz oku',readingOff:'Animasyonlu okumaya dön',letterLabel:'Mektubumun tamamı',finalChapter:'05 / BÜTÜN YILDIZLAR BİZİMLE',finalTitle:'İyi ki doğdun,|aşkım.',birthday:'İyi ki doğdun, Tütüşüm',last:'Son bir şey daha…',replay:'Hikâyemizi yeniden yaşa ♡',footer:'Sadece senin için. Her zaman sevgiyle.',
  musicPlay:'Müziği aç',musicPause:'Müziği kapat',musicPlaying:'Müzik: açık',musicPaused:'Müzik: kapalı',photoDialog:'Büyütülmüş fotoğraf',closePhoto:'Fotoğrafı kapat',photoHint:'Kapatmak için Esc tuşuna bas veya arka plana dokun',photoHers:'Tütüş’ün portresi',photoTogether:'İkimizin fotoğrafı',enlarge:'Büyüt',photoError:'Bu fotoğraf yüklenemedi.',emptyPhotos:'Fotoğraflar yakında burada yerlerini alacak.',emptyLetter:'Mektup yakında burada olacak.',lastFallback:'Seni seviyorum. Bugün, yarın ve her gün.',loadError:'Mektubun geliyor… Bağlantını kontrol edip yeniden dene.',retry:'Yeniden dene',noMusic:'Mektubu sessizlik içinde de okuyabilirsin.',
  excerptIntro:'Belki de bugün',excerptStory:['Belki unuttu','Ama bekle','Ben senin erkeğinim','Suriyelinin hiçbir şeyi unutmadığını'],excerptPortrait:'Gülüşünü',excerptTogether:'Birbirini aramadan'
 }
};
